# Imports
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"

# Empty lines
blank_lines_upper_bound = 2

# Comments
comment_width = 100
format_code_in_doc_comments = true